config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: "users/omniauth_callbacks" }

  root 'static_pages#home'
  resources :users, only: [:show, :index]
  resources :posts, only: [:create, :destroy, :index]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :friend_requests, only: [:create]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/friend_request.rb
class FriendRequest < ActiveRecord::Base
	belongs_to :friendship
	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"

	def accept
		self.update_attribute(:accepted, true)
	end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, class_name: "User"
	has_one :friend_request
	
	validates :user_id, uniqueness: { scope: :friend_id}
	validate :not_already_friends

	def add_inverse_friendship
		Friendship.create(user_id: self.friend_id, friend_id: self.user_id)
	end

	def not_already_friends
	end
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user

	has_many :likes
	has_many :comments

	validates :body, length: { minimum: 1 }

	def users_that_like
		users = []
		self.likes.each do |like|
			users << like.user
		end
		users
	end

	def names_of_likers
		likers = []
		self.users_that_like.each do |user|
			likers << user.name
		end
		likers.join(", ")
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook] 

  has_many :friendships
  has_many :friends, through: :friendships

  has_many :recieved_friend_requests, class_name: "FriendRequest", foreign_key: "recipient_id"
  has_many :sent_friend_requests, class_name: "FriendRequest", foreign_key: "sender_id"

  has_many :posts
  has_many :likes
  has_many :comments
  
  def pending_friend_requests
    self.recieved_friend_requests.where(accepted: false)
  end

  def feed
    Post.where("user_id IN (?)", self.friends.ids << self.id).order(created_at: :desc)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      user.image_url = auth.info.image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #change routing behavior after logging in with devise
  def after_sign_in_path_for(resource)
  	if resource.is_a?(User)
  		root_path
  	else
  		super
  	end
  end

  def after_sign_out_path_for(resource)
  	new_user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@comment = Comment.new(comment_params)
		if @comment.save
			flash[:success] = "Comment posted"
			redirect_to root_path
		else
			flash.now[:danger] = "Unable to post comment"
			render root_path
		end
	end

	def destroy
	end

	private

	def comment_params
		params.require(:comment).permit(:user_id, :post_id, :body)
	end

end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
	def create
		@friend_request = FriendRequest.new(friend_request_params)
		if @friend_request.save
			flash[:success] = "Friend Request sent"
			redirect_to User.find_by(id: @friend_request.recipient_id)
		else
			flash.now[:danger] = "Could not send friend request"
			redirect_to current_user
		end
	end

	private

	def friend_request_params
		params.require(:friend_request).permit(:sender_id, :recipient_id)
	end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

	def create
		friend_request = FriendRequest.find(params[:friendship][:friend_request_id])
		@friendship = friend_request.create_friendship(user_id: friend_request.sender_id, friend_id: friend_request.recipient_id)
		if @friendship.save
			friend_request.accept
			@friendship.add_inverse_friendship
			flash[:success] = "Added Friend"
			redirect_to @friendship.friend
		else
			flash.now[:danger] = "Unable to add friend"
			render friend_request.recipient
		end
	end

	def destroy

	end

	private

	def friendship_params
		params.require(:friendship).permit(:friend_request_id)
	end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	def create
		@like = Like.new(like_params)
		if @like.save
			redirect_to root_path
		else
			flash.now[:danger] = "Unable to like?"
			render root_path
		end
	end

	def destroy
		Like.find(params[:id]).destroy
		redirect_to root_path
	end

	private

	def like_params
		params.require(:likes).permit(:user_id, :post_id)
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			flash[:success] = "Posted"
			redirect_to root_path
		else
			flash.now[:danger] = "Failed to post"
			render 'static_pages/home'
		end
	end

	def destroy
	end

	def index
		@posts = Post.all
	end

	private

	def post_params
		params.require(:post).permit(:body)		
	end


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	def create
		super
		UserMailer.welcome_email(@user).deliver_later if resource.save
	end

	private

	def sign_up_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
		
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
		@post = current_user.posts.build if user_signed_in?
		@feed = current_user.feed if user_signed_in?
	end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def facebook
		@user = User.from_omniauth(request.env["omniauth.auth"])

		if @user.persisted?
			sign_in_and_redirect @user
		else
			session["devise.facebook_data"] = request.env["omniauth.auth"]
			redirect_to new_user_registration_url
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def new
		@user = User.new			
	end	

	def show
		@user = User.find(params[:id])
		@friend_requests = @user.pending_friend_requests
	end

	def index
		@users = User.all.order(name: :asc)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(partial)
		base = "Odin Facebook Clone"
		if !partial.empty?
			"#{partial} | #{base}"
		else
			base
		end
	end

	def avatar_for(user)
		"http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=48"
	end
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
	def friend_request_already_sent?(user1, user2)
		FriendRequest.find_by(sender_id: user1, recipient_id: user2) || FriendRequest.find_by(sender_id: user2, recipient_id: user1)	
	end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<li>
	<%= link_to comment.user.name, user_path(comment.user.id) %> |
	<%= comment.body %> |
	<%= time_ago_in_words(comment.created_at) %> ago
</li>

app/views/comments/_comment_form.html.erb
<%= form_tag '/comments' do %>
	<%= text_field_tag "comment[body]", nil, placeholder: "Add comment" %>
	<%= hidden_field_tag 'comment[user_id]', current_user.id %>
	<%= hidden_field_tag 'comment[post_id]', post[:id] %>
	<%= submit_tag "Submit" %>
<% end %>

app/views/friend_requests/_friend_request.html.erb
<li>
	<%= link_to "Accept", friendships_path(friendship: { friend_request_id: friend_request.id }), method: :post %> |
	<%= friend_request.sender.name %> | 
	<%= friend_request.sender.email %> | 
	<%= friend_request.sender.created_at %>
</li>

app/views/posts/_post.html.erb
<div class="post row col-xs-8">
	<div class="col-xs-2 avatar">
			<%= post.user.image_url.nil? ? image_tag(avatar_for(post.user), class: "img-responsive avatar") : image_tag(avatar_for(post.user.image_url), class: "img-responsive avatar") %>
	</div>
	<div class="row col-xs-10">
		<div class="col-xs-2">
			<%= link_to post.user.name, user_path(post.user.id) %>
		</div>
		<div class="col-xs-6">
			<%= post.body %>
		</div>
		<div class="col-xs-2">
			<%= post.created_at %>
		</div>
	</div>
	<div class="row col-xs-10">
	<div class="col-xs-4">
		<% if post.users_that_like.include?(current_user) %>
		<%= link_to "Unlike", like_path(id: Like.find_by(user_id: current_user.id, post_id: post.id)), method: :delete %>
		<% else %>
			<%= link_to "Like", likes_path(likes: { post_id: post.id, user_id: current_user.id }), method: :post %>
		<% end %>
		<% if post.likes.any? %>
			Liked by: <%= post.names_of_likers %>
		<% end %>
	</div>
</div>
</div>

app/views/posts/_post_form.html.erb
<%= form_for @post, html: { class: "form-inline row"} do |f| %>
	<div class="form-group col-xs-10">
		<%= f.text_area :body, class: "form-control", placeholder: "Add post here" %>
	</div>
	<div class="form-group col-xs-2">
		<%= f.submit "Post", class: "btn btn-default", id: "post-submit" %>
	</div>
<% end %>

app/views/static_pages/home.html.erb
<div class="container">
	<% if user_signed_in? %>
		<div class="post-form">
			<%= render 'posts/post_form' %>
		</div>
		<h1>News Feed</h1>	
		<div class="feed">
			<%= render @feed %>
		</div>
	<% else %>
		<h1>Odin Facebook Clone</h1>
	<% end %>
</div>

app/views/users/index.html.erb
<div class="container">
	<h1>All Users</h1>

	<table>
		<tr>
			<th></th>
			<th>Name</th>
			<th>Email</th>
		</tr>
	<% @users.each do |user| %>
		<tr>
			<td><%= user.image_url.nil? ? image_tag(avatar_for(user)) : image_tag(user.image_url)%></td>
			<td><%= link_to user.name, user_path(user.id) %></td>
			<td><%= user.email %></td>
			<%= render partial: 'shared/add_friend_partial.html.erb', locals: { user: user } %>
		</tr>
	<% end %>
</table>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<div class="container">
	<div class="info">
		<h1><%= @user.image_url.nil? ? image_tag(avatar_for(@user)) : image_tag(@user.image_url) %>
		<%= @user.name %>'s Profile</h1>
	</div>

	<% if @user == current_user %>
		<div class="dashboard">
			<% if @user.pending_friend_requests.any? %>
				<h3>Pending Friend Requests: <%= @friend_requests.count %></h3>
					<ul class="friend_requests">
						<%= render @friend_requests %>
					</ul>
			<% end %>
		</div>
	<% end %>


	<%= render partial: 'shared/add_friend_partial', locals: { user: @user } %>

	<div class="posts">
		<% @user.posts.each do |post| %>
			<%= render post %>
		<% end %>
	</div>
</div>